### PR TITLE
Remove deprecated allowpaymentrequest attribute

### PR DESCRIPTION
**Pull request by marcoscaceres**
Plan is to remove it from the platform: 

Payment Request: https://github.com/w3c/payment-request/pull/928 
HTML: https://github.com/whatwg/html/pull/5915

Updated tests: https://github.com/web-platform-tests/wpt/pull/25559

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Re: IPR, I applied to be a IE for the group. Not sure who the team contact is? @sideshowbarker can maybe press the right button?🙏

**Comment by sideshowbarker** [comment]
> Re: IPR, I applied to be a IE for the group. Not sure who the team contact is? @sideshowbarker can maybe press the right button?🙏

I think we need @wseltzer for this

**Comment by marcoscaceres** [comment]
Blocked on whatwg/html#5915

**Comment by marcoscaceres** [comment]
Updated tests https://github.com/web-platform-tests/wpt/pull/25559

**Comment by danyao** [comment]
@clelland WDYT?

**Comment by clelland** [comment]
+1 to remove this; it was specced *just* before feature policy became a thing.

I saw "blocked on" above, so held off the review. Since that's landed, I'll merge this now.

Thanks, @marcoscaceres

**Comment by clelland** [comment]
@wseltzer, is there something to do to placate ash-nazg here? I've revalidated, but the computer still says no.

**Comment by wseltzer** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by wseltzer** [comment]
I marked it as non-substantive, as it doesn't add IPR surface.

**Comment by clelland** [comment]
It removes some, so I wasn't sure if that counted just as much.

Thanks for unblocking that, @wseltzer!

**Pull request merged**
